// // config
export const data = {
  data: {
    images: {
      base_url: "http://image.tmdb.org/t/p/",
      secure_base_url: "https://image.tmdb.org/t/p/",
      backdrop_sizes: ["w300", "w780", "w1280", "original"],
      logo_sizes: ["w45", "w92", "w154", "w185", "w300", "w500", "original"],
      poster_sizes: ["w92", "w154", "w185", "w342", "w500", "w780", "original"],
      profile_sizes: ["w45", "w185", "h632", "original"],
      still_sizes: ["w92", "w185", "w300", "original"],
    },
    change_keys: [
      "adult",
      "air_date",
      "also_known_as",
      "alternative_titles",
      "biography",
      "birthday",
      "budget",
      "cast",
      "certifications",
      "character_names",
      "created_by",
      "crew",
      "deathday",
      "episode",
      "episode_number",
      "episode_run_time",
      "freebase_id",
      "freebase_mid",
      "general",
      "genres",
      "guest_stars",
      "homepage",
      "images",
      "imdb_id",
      "languages",
      "name",
      "network",
      "origin_country",
      "original_name",
      "original_title",
      "overview",
      "parts",
      "place_of_birth",
      "plot_keywords",
      "production_code",
      "production_companies",
      "production_countries",
      "releases",
      "revenue",
      "runtime",
      "season",
      "season_number",
      "season_regular",
      "spoken_languages",
      "status",
      "tagline",
      "title",
      "translations",
      "tvdb_id",
      "tvrage_id",
      "type",
      "video",
      "videos",
    ],
  },
  status: 200,
  statusText: "",
  headers: {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "*",
    "alt-svc": 'h3=":443"; ma=86400',
    "cache-control": "public, max-age=43200",
    "content-encoding": "br",
    "content-type": "application/json;charset=utf-8",
    date: "Sat, 20 Jul 2024 20:03:22 GMT",
    etag: 'W/"8ee6fd095d2be6e301251d766501a916"',
    server: "openresty",
    vary: "Accept-Encoding,accept-encoding",
    via: "1.1 d276e54ab5a1f0a1e054e54a253e8686.cloudfront.net (CloudFront)",
    "x-amz-cf-id": "DZc45w6b_Cdkju500p_WNxk_qW5aQ6-l4pcM9W6j8uDCg-0h4bxkAw==",
    "x-amz-cf-pop": "DEL54-P5",
    "x-cache": "Miss from cloudfront",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    adapter: ["xhr", "http", "fetch"],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: "application/json, text/plain, */*",
      Authorization:
        "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxZjg1OWM2NmI0YWU3NzU1MDdlOTVmMTI4YjA5MzAyZiIsIm5iZiI6MTcyMTUwNTYwNS44NjMwODEsInN1YiI6IjY2OWMxNDRlYWJlNzRkMDY0NTRiOWU1MiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.O7tNNL3CycjLgc0pOLq_vsLMQvddEhNo0WQkGsnc9gk",
    },
    baseURL: "https://api.themoviedb.org/3",
    method: "get",
    url: "/configuration",
  },
  request: {},
};
// // trending
export const bannerData = {
  data: {
    page: 1,
    results: [
      {
        backdrop_path: "/7cqKGQMnNabzOpi7qaIgZvQ7NGV.jpg",
        id: 76479,
        name: "The Boys",
        original_name: "The Boys",
        overview:
          "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
        poster_path: "/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg",
        media_type: "tv",
        adult: false,
        original_language: "en",
        genre_ids: [10765, 10759],
        popularity: 3784.897,
        first_air_date: "2019-07-25",
        vote_average: 8.474,
        vote_count: 9990,
        origin_country: ["US"],
      },
      {
        backdrop_path: "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
        id: 653346,
        title: "Kingdom of the Planet of the Apes",
        original_title: "Kingdom of the Planet of the Apes",
        overview:
          "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
        poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [878, 12, 28],
        popularity: 1526.548,
        release_date: "2024-05-08",
        video: false,
        vote_average: 7.132,
        vote_count: 1950,
      },
      {
        backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
        id: 786892,
        title: "Furiosa: A Mad Max Saga",
        original_title: "Furiosa: A Mad Max Saga",
        overview:
          "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
        poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [28, 12, 878],
        popularity: 1792.329,
        release_date: "2024-05-22",
        video: false,
        vote_average: 7.647,
        vote_count: 2215,
      },
      {
        backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
        id: 94997,
        name: "House of the Dragon",
        original_name: "House of the Dragon",
        overview:
          "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
        poster_path: "/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
        media_type: "tv",
        adult: false,
        original_language: "en",
        genre_ids: [10765, 18, 10759],
        popularity: 2341.394,
        first_air_date: "2022-08-21",
        vote_average: 8.4,
        vote_count: 4444,
        origin_country: ["US"],
      },
      {
        backdrop_path: "/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
        id: 1022789,
        title: "Inside Out 2",
        original_title: "Inside Out 2",
        overview:
          "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [16, 10751, 12, 35],
        popularity: 5100.537,
        release_date: "2024-06-11",
        video: false,
        vote_average: 7.683,
        vote_count: 1933,
      },
      {
        backdrop_path: "/kwronSXO1ogMqHHFvY2eBxfFLdn.jpg",
        id: 114479,
        name: "The Acolyte",
        original_name: "The Acolyte",
        overview:
          "A hundred years before the rise of the Empire, the Jedi Order and the Galactic Republic have prospered for centuries without war. During this time, an investigation into a shocking crime spree pits a Jedi Master against a dangerous warrior from his past.",
        poster_path: "/yuCKJsbzzadXh6tMUsIwZ2zaKXy.jpg",
        media_type: "tv",
        adult: false,
        original_language: "en",
        genre_ids: [9648, 10765],
        popularity: 713.982,
        first_air_date: "2024-06-04",
        vote_average: 5.7,
        vote_count: 350,
        origin_country: ["US"],
      },
      {
        backdrop_path: "/dvBCdCohwWbsP5qAaglOXagDMtk.jpg",
        id: 533535,
        title: "Deadpool & Wolverine",
        original_title: "Deadpool & Wolverine",
        overview:
          "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
        poster_path: "/jbwYaoYWZwxtPP76AZnfYKQjCEB.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [878, 28, 35],
        popularity: 748.36,
        release_date: "2024-07-24",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        backdrop_path: "/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
        id: 718821,
        title: "Twisters",
        original_title: "Twisters",
        overview:
          "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
        poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [28, 12, 53],
        popularity: 643.96,
        release_date: "2024-07-10",
        video: false,
        vote_average: 7.371,
        vote_count: 116,
      },
      {
        backdrop_path: "/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg",
        id: 748783,
        title: "The Garfield Movie",
        original_title: "The Garfield Movie",
        overview:
          "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
        poster_path: "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [16, 35, 10751, 12],
        popularity: 2053.649,
        release_date: "2024-04-30",
        video: false,
        vote_average: 7.263,
        vote_count: 498,
      },
      {
        backdrop_path: "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
        id: 280180,
        title: "Beverly Hills Cop: Axel F",
        original_title: "Beverly Hills Cop: Axel F",
        overview:
          "Forty years after his unforgettable first case in Beverly Hills, Detroit cop Axel Foley returns to do what he does best: solve crimes and cause chaos.",
        poster_path: "/zszRKfzjM5jltiq8rk6rasKVpUv.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [28, 35, 80],
        popularity: 1214.968,
        release_date: "2024-06-20",
        video: false,
        vote_average: 6.904,
        vote_count: 627,
      },
      {
        backdrop_path: "/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg",
        id: 519182,
        title: "Despicable Me 4",
        original_title: "Despicable Me 4",
        overview:
          "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
        poster_path: "/3w84hCFJATpiCO5g8hpdWVPBbmq.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [16, 10751, 35, 28],
        popularity: 3949.4,
        release_date: "2024-06-20",
        video: false,
        vote_average: 7.371,
        vote_count: 333,
      },
      {
        backdrop_path: "/xFJS2FeCfCztFWO9yEW0RV2uFz.jpg",
        id: 77169,
        name: "Cobra Kai",
        original_name: "Cobra Kai",
        overview:
          "This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.",
        poster_path: "/6GDW4EsgsXlYrL1ASb5eCHQK4er.jpg",
        media_type: "tv",
        adult: false,
        original_language: "en",
        genre_ids: [10759, 18, 35],
        popularity: 1858.399,
        first_air_date: "2018-05-02",
        vote_average: 8.216,
        vote_count: 6028,
        origin_country: ["US"],
      },
      {
        backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
        id: 1048241,
        title: "My Spy the Eternal City",
        original_title: "My Spy the Eternal City",
        overview:
          "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
        poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [28, 35],
        popularity: 196.136,
        release_date: "2024-07-18",
        video: false,
        vote_average: 6.982,
        vote_count: 55,
      },
      {
        backdrop_path: "/ybn3jCia5XBD0ZgEM07gcUPuRNh.jpg",
        id: 508883,
        title: "The Boy and the Heron",
        original_title: "君たちはどう生きるか",
        overview:
          "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
        poster_path: "/f4oZTcfGrVTXKTWg157AwikXqmP.jpg",
        media_type: "movie",
        adult: false,
        original_language: "ja",
        genre_ids: [16, 12, 14],
        popularity: 442.792,
        release_date: "2023-07-14",
        video: false,
        vote_average: 7.515,
        vote_count: 1461,
      },
      {
        backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
        id: 693134,
        title: "Dune: Part Two",
        original_title: "Dune: Part Two",
        overview:
          "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
        poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [878, 12],
        popularity: 403.782,
        release_date: "2024-02-27",
        video: false,
        vote_average: 8.165,
        vote_count: 4862,
      },
      {
        backdrop_path: "/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg",
        id: 974262,
        title: "Descendants: The Rise of Red",
        original_title: "Descendants: The Rise of Red",
        overview:
          "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
        poster_path: "/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [14, 12, 10751, 35],
        popularity: 2015.902,
        release_date: "2024-07-11",
        video: false,
        vote_average: 7.3,
        vote_count: 145,
      },
      {
        backdrop_path: "/a4IWRYNMNMszIkRbEIiNsRg6cvt.jpg",
        id: 929590,
        title: "Civil War",
        original_title: "Civil War",
        overview:
          "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
        poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [10752, 28, 18],
        popularity: 713.519,
        release_date: "2024-04-10",
        video: false,
        vote_average: 6.99,
        vote_count: 1923,
      },
      {
        backdrop_path: "/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
        id: 37854,
        name: "One Piece",
        original_name: "ワンピース",
        overview:
          'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
        poster_path: "/e3NBGiAifW9Xt8xD5tpARskjccO.jpg",
        media_type: "tv",
        adult: false,
        original_language: "ja",
        genre_ids: [10759, 35, 16],
        popularity: 185.797,
        first_air_date: "1999-10-20",
        vote_average: 8.722,
        vote_count: 4524,
        origin_country: ["JP"],
      },
      {
        backdrop_path: "/vX71TGviqLsOtDNJ9q1QR4m14kH.jpg",
        id: 218589,
        name: "Those About to Die",
        original_name: "Those About to Die",
        overview:
          "Within the spectacular, complex and corrupt world of gladiatorial sports in Ancient Rome, follow an ensemble of diverse characters across the many layers of Roman society where sports, politics and business intersect and collide.",
        poster_path: "/gvz0m4MJ8sAj6yMcQdwN07bNjRY.jpg",
        media_type: "tv",
        adult: false,
        original_language: "en",
        genre_ids: [18],
        popularity: 206.255,
        first_air_date: "2024-07-18",
        vote_average: 8.167,
        vote_count: 12,
        origin_country: ["US"],
      },
      {
        backdrop_path: "/wXx72bbhhnfORmlSNMWR28fPd8b.jpg",
        id: 1086747,
        title: "The Watchers",
        original_title: "The Watchers",
        overview:
          "A young artist gets stranded in an extensive, immaculate forest in western Ireland, where, after finding shelter, she becomes trapped alongside three strangers, stalked by mysterious creatures each night.",
        poster_path: "/vZVEUPychdvZLrTNwWErr9xZFmu.jpg",
        media_type: "movie",
        adult: false,
        original_language: "en",
        genre_ids: [14, 9648, 53, 27],
        popularity: 350.838,
        release_date: "2024-06-06",
        video: false,
        vote_average: 6.533,
        vote_count: 514,
      },
    ],
    total_pages: 1000,
    total_results: 20000,
  },
  status: 200,
  statusText: "",
  headers: {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "*",
    "alt-svc": 'h3=":443"; ma=86400',
    "cache-control": "public, max-age=254",
    "content-encoding": "br",
    "content-type": "application/json;charset=utf-8",
    date: "Sat, 20 Jul 2024 20:03:22 GMT",
    etag: 'W/"179f9be4ad92576330cdc5ef07b8111b"',
    server: "openresty",
    vary: "Accept-Encoding,accept-encoding",
    via: "1.1 d276e54ab5a1f0a1e054e54a253e8686.cloudfront.net (CloudFront)",
    "x-amz-cf-id": "TDSUqZwz9syMUQLudgLEhWRD461XjttCK04HXTePEyuZ-DO66wCncQ==",
    "x-amz-cf-pop": "DEL54-P5",
    "x-cache": "Miss from cloudfront",
    "x-memc": "HIT",
    "x-memc-age": "346",
    "x-memc-expires": "254",
    "x-memc-key": "f79d1cb8378c4218d6c84e42a2af61c8",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    adapter: ["xhr", "http", "fetch"],
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {},
    headers: {
      Accept: "application/json, text/plain, */*",
      Authorization:
        "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxZjg1OWM2NmI0YWU3NzU1MDdlOTVmMTI4YjA5MzAyZiIsIm5iZiI6MTcyMTUwNTYwNS44NjMwODEsInN1YiI6IjY2OWMxNDRlYWJlNzRkMDY0NTRiOWU1MiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.O7tNNL3CycjLgc0pOLq_vsLMQvddEhNo0WQkGsnc9gk",
    },
    baseURL: "https://api.themoviedb.org/3",
    method: "get",
    url: "/trending/all/week",
  },
  request: {},
};
